# This is a basic workflow that is manually triggered

name: Move open issues to the current project iteration
on:
  workflow_call:
    inputs:
      iteration_field_name:
        description: "The iteration field name as configured in your project settings."
        required: true
        type: string
      excluded_statuses:
        description: "Comma-separated list of statuses. Do not move issues with these statuses."
        default: "Done"
        required: false
        type: string

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@v0.5.0
        with:
          owner: odomero
          number: 1
          # This token is a organization configured token
          token: ''
          iteration-field: ${{ inputs.iteration_field_name }}
          iteration: last
          new-iteration: current
          excluded-statuses: ${{ inputs.excluded_statuses }}
