# This is a basic workflow that is manually triggered

name: Move issues

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
    - uses: odomero/github-workflows/.github/workflows/move_issues.yml@v1.0.0
      with:
        project_id: 1
        iteration-field: "Sprint"
        iteration: last
        new-iteration: current
        excluded-statuses: "Done"
